### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by AlanKeiss** [react-spring/gltfjsx#10]
Hello,
I would love to use this tool but every time I run:
`npx gltfjsx scene.gltf`

I get:
`npx: installed 129 in 4.325s`
`Unexpected token`

I have tested on various files,  parameters, with or without putting the file in a /public subfolder.
Maybe my problem is related to the readme line `You need to be set up for asset loading` which I don't understand.

Thank you.

**Comment by AlanKeiss** [comment]
=> Switching Node version from 8 to 12 solved everything

**Comment by drcmda** [comment]
nice, great that you could solve it! maybe im relying on some newer javascript features, didn't bablify the lib.
