### ISSUE TITLE
Model renders as empty group

### ISSUE THREAD

**Issue by cor-rine** [react-spring/gltfjsx#15]
Exporting my glb file and running the script renders the following file as output:

```javascript
/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/sheep.glb')
  return <group ref={group} {...props} dispose={null}></group>
}
```

Though, I do notice that my glb file is quite small, and I'm assuming my export is the actual cause of the problem.  Is there a particular render or scene setting I should be making sure is true before I export?

**Comment by drcmda** [comment]
could you upload the glb somewhere? i can take a look

**Comment by cor-rine** [comment]
Thanks for the quick response - and for the link!  It seems something is off with my files:
https://www.dropbox.com/sh/nigh8m2yzd1i0fg/AAA2OU6lKB58Q_ZztaC9aVNMa?dl=0

I also included the blender file in that download link if you have some time to dig a little deeper.  Appreciate it!

**Comment by cor-rine** [comment]
Closing this issues as resolved.
It turns out to be a known problem with the glTF 2.0 Exporter: Selected object does not get exported if the parent is also not selected.

Details: https://github.com/KhronosGroup/glTF-Blender-IO/issues/1066#issuecomment-628102833
