### ISSUE TITLE
Cannot set --compress value to false

### ISSUE THREAD

**Issue by Teo0303** [react-spring/gltfjsx#17]
I'm trying to convert[ this ](https://github.com/Rawdreen/showroom/blob/master/model/Room_2.gltf)gltf model to jsx component. 

I tried to set --compress=false, but it doesn't help. Whatever I do, it removes names from meshes.

![image](https://user-images.githubusercontent.com/39439363/81249538-4cd7c980-9038-11ea-9ac6-6fa66d946b4e.png)

Is there problem with model itself or Have I ran the npx command wrong?

**Comment by drcmda** [comment]
seems like a small bug, i'll take a look

**Comment by drcmda** [comment]
as a quick workaround you can do compress=0, looks like it turns "false" to a string.

**Comment by drcmda** [comment]
never mind its fixed

**Comment by Teo0303** [comment]
Thanks dear!
