### ISSUE TITLE
A syntax error has occurred

### ISSUE THREAD

**Issue by BYODKM** [react-spring/gltfjsx#2]
When I take my gltf file into gltfjsx, it happen.

```
$ npx gltfjsx input.gltf Output.js

ArrayBuffer { byteLength: 32830 }
SyntaxError: The string did not match the expected pattern.
```

I checked the file on a validator below, it says "valid".
http://github.khronos.org/glTF-Validator/

Please give me a clue.

**Comment by drcmda** [comment]
could you upload the gltf somewhere?

**Comment by BYODKM** [comment]
I'm afraid not. Thanks!

**Comment by drcmda** [comment]
nothing i can do without a testcase. the gltf loader wasnt made for node and i had to rip out parts to make it work, but there's probably still something in it that wasn't to make an ajax request or something of that sort, or use browser api.

**Comment by vxna** [comment]
Can repro with [DamagedHelmet](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/DamagedHelmet/glTF) from glTF-Sample-Models tho.

**Comment by drcmda** [comment]
my current observation is that if you pack multi-file gltf's into single file gltfs via gltf-pipeline it seems to work.

**Comment by jvink** [comment]
Same issue, I use [Newpaper](https://sketchfab.com/3d-models/folded-newspaper-4fc14ea5129b4ea3b34a22844a6f1b3f) model.

Does not work for me. I click download and use the Autoconverted format (glTF).

**Comment by drcmda** [comment]
did you try gltf-pipeline?

**Comment by BYODKM** [comment]
I forgot to mention. The `gltf-pipeline` worked for me.

**Comment by drcmda** [comment]
pushed a bugfix, i hope that solves it. worked with that newspaper model at least (without gltf-pipeline)
