### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by cristianvj** [react-spring/gltfjsx#20]
Hello, first I want to congratulate you on the tool. Secound I'm using Next.js and charge this compilated component

```
/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/clothw.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.lambert2SG} geometry={nodes.Object_3.geometry} scale={[0.03, 0.03, 0.03]} />
      <mesh material={materials.lambert2SG} geometry={nodes.Object_4.geometry} />
    </group>
  )
}
```

But I have this error:

> 1 | module.exports = require("three/examples/jsm/loaders/GLTFLoader");

__webpack_require__
./webpack/bootstrap:21
  
>18 | // Execute the module function
  19 | var threw = true;
  20 | try {
 |> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];

**Comment by drcmda** [comment]
this is threes fault unfortunately. you can open a bug report on their GH.

see: https://discourse.threejs.org/t/can-not-load-gltfloader-in-nextjs-application/12317/8?u=drcmda

**Comment by neefrehman** [comment]
i ran into this problem with Next recently and found that dynamic `import()` + `React.lazy()` solved the problem for me. more details here: https://github.com/react-spring/react-three-fiber/discussions/504
