### ISSUE TITLE
Coordinate rounding with larger models results in object offsets. 

### ISSUE THREAD

**Issue by BryanChrisBrown** [react-spring/gltfjsx#25]
I believe since gltfjsx parses coordinates out to two decimals, (10.00) it causes objects to move in models with larger scales. Normally these minute movements wouldn't be noticeable, but in my case it causes architectural elements, like sidewalks or site maps to be offset by a few inches, which results in gaps in my model. 

Images attached: 
Don Mccurdy GLTF Viewer
<img width="405" alt="Screen Shot 2020-08-07 at 10 15 44 AM" src="https://user-images.githubusercontent.com/22871421/89654657-f6786200-d896-11ea-8816-9c244473fe17.png">
GLTF-JSX
<img width="308" alt="Screen Shot 2020-08-07 at 10 16 43 AM" src="https://user-images.githubusercontent.com/22871421/89654732-1a3ba800-d897-11ea-93d3-a4765223e342.png">

**Comment by drcmda** [comment]
oh, yes, and you can change it: 

```text
 --precision, -p     Number of fractional digits         [number ] [default: 2]
```

**Comment by BryanChrisBrown** [comment]
Thanks! I must've read right past that in the docs. 😅

The first screen capture was using Don Mccurdy's GLTF viewer which has an orange town/sunset hdri for reflections. I'm using a different hdri in the second screen capture, along with baking all the geometry in 3ds Max/Vray so I don't have to rely on Three's realtime shadowing. There's also a bit of gamma control and fog
