### ISSUE TITLE
Issue with distorted meshes

### ISSUE THREAD

**Issue by Code47X** [react-spring/gltfjsx#26]
I'm having an issue with my model being distorted after turning it into a JSX component. I have one glb file with all the scene's meshes, but it seems like some of them are not being scaled/positioned correctly (At least I think that's the issue?). Not sure where exactly the problem is stemming from, just wondering if you had any insight on a possible cause?

When viewing the glb in a model viewer it appears correctly:
![model](https://user-images.githubusercontent.com/5169367/89717905-762e2b80-d980-11ea-9d95-99ba6ee2b4b8.png)

After creating the JSX:
![model2](https://user-images.githubusercontent.com/5169367/89717922-98c04480-d980-11ea-8ceb-45553ca894ac.png)

PS: Thank you for your work :+1:

**Comment by drcmda** [comment]
could you try without the compress option? like disabling it. it tries to avoid "empty" objects but maybe it's overlooking something. if your scene is correct with compression disabled (see the options on the main page) then that must be it. in that case i would be glad if i could have the gltf for bug fixing.

**Comment by Code47X** [comment]
Appreciate the fast response. Just tried it with `npx gltfjsx gltf/ForestScene2.glb --types --compress=false` and I'm getting the same result. More than happy to send over the glb if you'd like to have a look.

**Comment by drcmda** [comment]
could you append it here?

**Comment by Code47X** [comment]
After debugging some more, it looks like its actually just an issue with the precision I was using. The source models were scaled down very small and I did not use the proper precision arg which resulted in some bad rounding.

**Comment by Code47X** [comment]
Everything's as expected! Closing this issue.
