### ISSUE TITLE
0.0.2 Converting GLB syntax error.

### ISSUE THREAD

**Issue by jwtea** [react-spring/gltfjsx#4]
In version 0.0.1 the loader was assigning the return to `const [gltf, objects]` however in 0.0.2 it's assigning to `const gltf`. 
This is then referenced in the JSX as `{...gltf.__$[1].geometry}`
Which causes `Uncaught TypeError: Cannot read property '1' of undefined`

Edit: From the console the contents of gltf are : 
```
(2) [{…}, Array(3)]
0: {scene: Scene, scenes: Array(1), animations: Array(0), cameras: Array(0), asset: {…}, …}
1: (3) [{…}, {…}, {…}]
length: 2
__proto__: Array(0)
```

**Comment by drcmda** [comment]
could you update reactthreefiber? there was a slight api change in useLoader. it's backwards compatible in r3f, but not in gltfjsx

**Comment by jwtea** [comment]
@drcmda awesome it's importing now thank you! Related https://github.com/react-spring/react-three-fiber/issues/216
