### ISSUE TITLE
Loading Model within NextJS or Storybook

### ISSUE THREAD

**Issue by robksawyer** [react-spring/gltfjsx#6]
I currently have a NextJS setup and the default path doesn't seem to work e.g. `/scene.gltf`. So, I just wanted to mention that after I changed this to `/public/models/gyoza/scene.gltf` it loaded the model. Unfortunately, setting up an ErrorBoundary didn't really help much either. 

Maybe an addition to the documentation to note this?

**Comment by drcmda** [comment]
it does mention it

    You need to be set up for asset loading and the actual GLTF has to be present in your /public folder.

but it's generally related to the threejs loader, useLoader and the component are just wraps around new THREE.GLTFLoader().load(url, gltf => ...)

**Comment by robksawyer** [comment]
Got this working just needed to update to the following.

```
...
export default function Model(props) {
  ...
  // model is inside of /public/models/my-model.glb
  const gltf = useLoader(GLTFLoader, '/models/my-model.glb')

  return (
   ....
  )
}
...
```

**Comment by pke** [comment]
And this approach would also work for react-native?
