### ISSUE TITLE
Artifacts when exporting

### ISSUE THREAD

**Issue by bitttttten** [react-spring/gltfjsx#7]
Before I go ahead, I am not entirely sure if this is a fault of gltfjsx's. Although I thought I would report it just incase.

After exporting my object and rendering it I notice some grey lines appearing at the top of the model. You can see a darker artifact in the screenshot below running below the time 9.41 and it gets thinner as it goes from left to right. There's also a lighter part above it, going through the time. I have played around with a lot of the material options from threejs, although this kind of texture work is still new to me so I wasn't able to work it out.

I used this to generate the jsx:

`gltfjsx iphone.glb iphone.js --compress`

And the artifact:

![Screenshot 2020-02-05 at 16 44 14](https://user-images.githubusercontent.com/19930241/73857320-0c00c680-4837-11ea-8404-3fc86190f3ad.png)

The source model looks fine, and I checked that all the vertices align correctly on the same Z axis (it was a lot of labour lol).

![Screenshot 2020-02-05 at 16 46 07](https://user-images.githubusercontent.com/19930241/73857433-3783b100-4837-11ea-9da1-9d1438717e13.png)

And the source image:

![Screenshot 2020-02-05 at 16 48 04](https://user-images.githubusercontent.com/19930241/73857490-4ec29e80-4837-11ea-8b71-98d4f2131798.png)

My scene is very simple:

```js
export const Phone = () => (
  <Canvas
    css={{
      top: 0,
      left: 0,
      width: `100%`,
      height: `100%`
    }}
    pixelRatio={devicePixelRatio}
  >
    <ambientLight intensity={0.68} />
    <pointLight position={[600, 600, 600]} intensity={0.475} />
    <Suspense
      fallback={
        <Dom>
          <div>
            Loading..
          </div>
        </Dom>
      }
    >
      <Model />
    </Suspense>
  </Canvas>
);

```

And my model looks like this: https://gist.github.com/bitttttten/95e792f046472dac880183af1fdfa0ee

Am I missing something? I am not sure what is causing the artifacts.

I am happy to supply more details like models, etc.!

**Comment by drcmda** [comment]
gltfjsx doesn't change or modify the data. it just structures it a bit with short access jsx, but the actual buffergeom comes directly from THREE.GLTFLoader. you can doublecheck by rendering:

```jsx
const gltf = useLoader(GLTFLoader, url)
return <primitive object={gltf.scene} dispose={null} />
```

which simply puts the scene into the graph without touching it. that should give you the same glitches. it's probably related to compression, or there is still some topology problem.

this for instance to me looks like an artifact:

<img width="423" alt="Screenshot 2020-02-05 at 22 54 15" src="https://user-images.githubusercontent.com/2223602/73886784-8860cd00-486a-11ea-9351-aa9e68e0feb4.png">

**Comment by bitttttten** [comment]
Yeah, I see those artifacts in Blender but they look different the ones in the browser. I was a bit confused about how they related to each other, if they did at all, as I don't have much experience with 3d models, blender, gltf.

Okay with `<primitive>` I get similar artifacts so it is not gltfjsx.

![Screenshot 2020-02-06 at 10 48 15](https://user-images.githubusercontent.com/19930241/73925452-600aba00-48ce-11ea-9677-886a26a851ca.png)

Happy to close this issue then since it's not related :)

**Comment by drcmda** [comment]
i believe what you see in blender is unrelated because the model is still going to get triangulated in gltf. in blender you have quads and ngons. maybe try triangulating in blender yourself: edit mode, sel all, face > triangulate

**Comment by bitttttten** [comment]
ahh thanks for the tip regarding triangulate. i noticed one of the vertixes was sticking out, although it didn't seem to fix my problem.

i noticed that the sharp edges were a bit inconsistent, and after playing around with them it seems to be related.

with every edge marked as sharp:

![Screenshot 2020-02-10 at 09 33 23](https://user-images.githubusercontent.com/19930241/74133329-a4f16200-4be8-11ea-897b-8514e65010e4.png)

with no smart edges:

![Screenshot 2020-02-10 at 09 33 49](https://user-images.githubusercontent.com/19930241/74133352-b0448d80-4be8-11ea-940b-f8896626f222.png)

both have artifacts of their own so it's not a finished solution but i'll keep digging and let you know if i solve it :)
