### ISSUE TITLE
TypeError: Cannot read property 'array' of undefined

### ISSUE THREAD

**Issue by simonghales** [react-spring/gltfjsx#8]
Hey there, absolutely love the work that's being done with this project and react-three-fiber. Thank you so much!

I'm trying to convert a gltf file but I always run into the same error.

```
THREE.BufferGeometry: .addAttribute() has been renamed to .setAttribute().
THREE.BufferGeometry: .addAttribute() now expects ( name, attribute ).
...
...
THREE.BufferGeometry: .addAttribute() has been renamed to .setAttribute().
THREE.BufferGeometry: .addAttribute() now expects ( name, attribute ).
TypeError: Cannot read property 'array' of undefined
    at /Users/simonhales/.npm/_npx/10218/lib/node_modules/gltfjsx/bin/GLTFLoader.js:1171:57
    at async Promise.all (index 0)
    at async Promise.all (index 1)
loader failed
```

The command I'm running is `npx gltfjsx Banana.gltf Banana.js --animation`

I've uploaded my files here https://drive.google.com/drive/folders/1pE7XhITz5oE-WrQKoRPva6bQ24Mmacx8?usp=sharing

Banana.gltf is exported straight from Blender.

bananaDraco.gltf has been converted via gltf-pipeline

I've also included the original Blender file.

I verified that the files could be viewed via https://gltf-viewer.donmccurdy.com/

I'm not the most experienced dev (especially when it comes to this kind of stuff), but I have some time off at the moment so I shall clone this repo and see if I'm able to make any progress with determining the issue.

Note: I tested using the example .glb file in this repo, which had no issues.

Edit:

Just to add, I'm able to load `Banana.gltf` just fine via the example from the react-three-fiber readme.

```
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
...
const gltf = useLoader(GLTFLoader, url)
...
```

**Comment by drcmda** [comment]
should be fixed!

**Comment by drcmda** [comment]
the other error should be gone too. 

it kind of sucks, gltfloader doesn't work under node and im basically just ripping out all the pieces that crash. i don't need it to actually create buffers, i just need the structure from it - there's probably an easier way: @donmccurdy

**Comment by drcmda** [comment]
also fixed support for bones. it will add the root bone as a raw primitive and wire up the skeleton of the skinnedmesh. here's an updated example (Stacy.js): https://codesandbox.io/s/r3f-bones-3i7iu

**Comment by donmccurdy** [comment]
> it kind of sucks, gltfloader doesn't work under node and im basically just ripping out all the pieces that crash. 

I've [hacked around the nodejs issues before](https://gist.github.com/donmccurdy/323c6363ac7ca8a7de6a3362d7fdddb4), but it took hacks all the way down. Draco is the hardest part — and that link is outdated, in that regard — because it now uses Web Workers. Open to ideas on fixing that.

Do you just need the JSON from the glTF file? Or the exact threejs object hierarchy that GLTFLoader would return?

**Comment by donmccurdy** [comment]
If the JSON is enough, I can share how to decode that from a `.glb` easily.

If you need a full threejs hierarchy, which would be the same as the glTF JSON plus some added leaf nodes, I'm guessing https://github.com/mrdoob/three.js/pull/18484 might help you out — write a plugin that "provides" all the buffers and textures with empty data, let the rest run normally.

**Comment by donmccurdy** [comment]
> If the JSON is enough, I can share how to decode that from a .glb easily.

Specifically: https://github.com/donmccurdy/glTF-Transform/blob/c6fa67080f7863f4ed79560ab1b812ccd8a73fbe/packages/core/src/util.ts#L35-L65

**Comment by drcmda** [comment]
> Do you just need the JSON from the glTF file? Or the exact threejs object hierarchy that GLTFLoader would return?

i think it would need to be the object hierarchy. i think relying on pure gltf would be the easiest when it comes to reading out, but emulating a basic threejs structure is probably going to be very hard.

the current workflow is based on the /bin directory in this repo, a fork of the loader and everything that ever wants to fetch requests for assets or create things that node can't is removed little by little. i think i oriented myself around the gist you posted, i saw it in the threejs discourse forum i believe.
