### ISSUE TITLE
GLTF Export from Blender 2.8 using GLTFJSX contains zero nodes or materials

### ISSUE THREAD

**Issue by robksawyer** [react-spring/gltfjsx#9]
I'm using the default GLTF export feature from Blender to export my model that is at a scale of `18.6` and it seems to not contain any `nodes` or `materials` after converting via the `gltfjsx` conversion. Using `react-three-fiber` version `^4.0.9`.

The following is what I'm seeing. What am I doing wrong?

**GLB Code (when I remove spread operator and just assign a variable)**
<img width="1339" alt="Screen Shot 2020-02-06 at 8 24 30 AM" src="https://user-images.githubusercontent.com/179419/73956736-38115b80-48ba-11ea-90c9-9a10b7df19ad.png">
<img width="872" alt="Screen Shot 2020-02-06 at 8 25 02 AM" src="https://user-images.githubusercontent.com/179419/73956744-3ba4e280-48ba-11ea-837f-1e7c242d5721.png">

**Conversion code**
```
// Auto-generated by https://github.com/react-spring/gltfjsx

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/models/round-logo.glb')

  console.log('nodes', nodes)
  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Scene">
        <mesh
          material={materials['Material']}
          geometry={nodes['Curve004'].geometry}
          name="Curve004"
          rotation={[Math.PI / 2, 0, 0]}
          scale={[10, 0, 10]}
        />
      </scene>
    </group>
  )
}
```

**Comment by drcmda** [comment]
needs an update of r3f, then it will work

**Comment by robksawyer** [comment]
I ran `yarn add react-three-fiber@latest` and that did the trick. I previously tried using `4.0.12` and that didn't work. Maybe an update to the docs to eliminate confusion? Thanks for the help, loving everything! Nice work!
